// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.themoviedb.org/3',
  api_key: 'feb6f0eeaa0a72662967d77079850353',
  movieImageResourceURL: 'https://www.themoviedb.org/t/p/w600_and_h900_face',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
